CREATE TYPE user_status AS ENUM (
    'Single',
    'Married',
    'Divorced',
    'Separated',
    'Widow',
);

CREATE TYPE user_gender AS ENUM (
    'Male',
    'Female',
    'Other'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(36) NOT NULL,
    status user_status,
    occupation VARCHAR(100),
    summary VARCHAR(255),
    gender user_gender,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);