<<<<<<< HEAD
DROP TYPE IF EXISTS marital_choices;
DROP TYPE IF EXISTS gender_choices;

CREATE TYPE marital_choices AS ENUM(
=======
CREATE TYPE user_status AS ENUM (
>>>>>>> feature/users-api
    'Single',
    'Married',
    'Divorced',
    'Separated',
<<<<<<< HEAD
    'Widow'
);

CREATE TYPE gender_choices AS ENUM(
    'Male',
    'Female',
    'Trans Male',
    'Trans Female',
    'Other'
);


=======
    'Widow',
);

CREATE TYPE user_gender AS ENUM (
    'Male',
    'Female',
    'Other'
);

>>>>>>> feature/users-api
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(36) NOT NULL,
<<<<<<< HEAD
    marital_status marital_choices NOT NULL,
    occupation VARCHAR(100),
    bio VARCHAR(255),
    gender gender_choices NOT NULL,
=======
    status user_status,
    occupation VARCHAR(100),
    summary VARCHAR(255),
    gender user_gender,
>>>>>>> feature/users-api
    date_created TIMESTAMP DEFAULT now() NOT NULL
);