DROP TYPE IF EXISTS marital_choices;
DROP TYPE IF EXISTS gender_choices;

CREATE TYPE marital_choices AS ENUM(
    'Single',
    'Married',
    'Divorced',
    'Separated',
    'Widow'
);

CREATE TYPE gender_choices AS ENUM(
    'Male',
    'Female',
    'Trans Male',
    'Trans Female',
    'Other'
);


CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(36) NOT NULL,
    marital_status marital_choices NOT NULL,
    occupation VARCHAR(100),
    bio VARCHAR(255),
    gender gender_choices NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);